<a href="https://colab.research.google.com/github/Calebchike/PVT-Extraction-Adjustment-Project/blob/with-functions/PVT_workbook_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Modules**

In [4]:
import openpyxl
import pandas as pd

# **Import Excel Data**

In [24]:
# Load the Excel file
file_path = "/content/PVT_Workbook .xlsx"
all_sheets = pd.read_excel(file_path, sheet_name=None)

# See the names of all worksheets
print("Worksheet names:", all_sheets.keys())

# Convert all worksheets to DataFrame
summary_df = all_sheets['Summary']
cce_df = all_sheets['CCE']
dle_df = all_sheets['DLE']
sep_df = all_sheets['Separator Tests']

Worksheet names: dict_keys(['Summary', 'CCE', 'DLE', 'Separator Tests'])

# **Summary**

In [26]:
summary_df.head(5)

             Well information   Value
0  Initial Reservoir Pressure  4089.7
1       Reservoir Temperature   207.2
2        Reservoir Fluid mol%    52.9
3     Reservoir Fluid Mol Wt.  122.05
4       Bubble Point Pressure     988

# **Constant Composition Expansion (CCE)**

In [27]:
cce_df.head(5)

   Pressure  Relative Volume  Density  Y-Function  Compressibility
0      5500           0.9524   0.7663         NaN         0.000008
1      5000           0.9563   0.7632         NaN         0.000009
2      4500           0.9610   0.7595         NaN         0.000009
3      4090           0.9645   0.7567         NaN         0.000010
4      3500           0.9705   0.7520         NaN         0.000011

# **Differential Liberation Experiment (DLE)**

In [28]:
dle_df.head(5)

,Pressure,Rs,Bo,Oil Density,Bg,Gas Viscosity,Gas Density,Gas Z-Factor
0,5500,261.5,1.159,0.7663,NaN,NaN,NaN,NaN
1,5000,261.5,1.163,0.7632,NaN,NaN,NaN,NaN
2,4500,261.5,1.169,0.7595,NaN,NaN,NaN,NaN
3,4090,261.5,1.173,0.7567,NaN,NaN,NaN,NaN
4,3500,261.5,1.181,0.7520,NaN,NaN,NaN,NaN